services:
    db:
        image: postgis/postgis:12-3.4
        container_name: gaj-db25
        #restart: always
        environment:
          POSTGRES_DB: gaj
          POSTGRES_USER: root
          POSTGRES_PASSWORD: pass123
        volumes:
          - ./keys/m_gaj.27-03-23.esquema.sql:/docker-entrypoint-initdb.d/init-db.sql
          # - ./data/pg:/var/lib/postgresql/data
          #- ./keys/m_gaj.27-03-23.esquema.sql:/esquema.sql
        ports:
          - "5432:5432"
    java:
      container_name: gaj-service25
      image: gaj-service:2.5
      ports:
        - 8080:8080
        - 8083:8083
      volumes:
        - ./gaj-server-main:/gaj-server-main
        - ./conf/compilar.sh:/usr/local/bin/compilar.sh
        #- ./keys/server.xml:/opt/tomcat/conf/server.xml
        - ./keys/sqlhosts:/etc/sqlhosts
        - ./keys/m2-settings-v2.xml:/root/.m2/settings.xml
        #- ./conf/python-scripts:/root/python
        - ./conf/homeroot:/root
        - ./conf/tomcat-users.xml:/etc/tomcat9/tomcat-users.xml
        - ./conf/homeroot/tmf.war:/var/lib/tomcat9/webapps/tmf.war
        #- ./keys/application-uat2.yml.mainjuzgamiento:/etc/application.yml
        - ./keys/aplication.yml:/etc/application.yml
    front:
      container_name: gaj-front4116
      image: gaj-front:4.1.16
      ports:
        - 4200:4200
      volumes:
        - ./conf/compilar-front.sh:/usr/local/bin/compilar-front.sh
        #- ./gaj-frontend:/gaj-frontend
    